name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: sw-ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          echo target-branch: main > ./config.yml
          echo helm-extra-args: --timeout 600 >> ./config.yml
          echo validate-maintainers: false >> ./config.yml
          changed=$(ct list-changed --config ./config.yml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          echo target-branch: main > ./config.yml
          echo helm-extra-args: --timeout 600 >> ./config.yml
          echo validate-maintainers: false >> ./config.yml
          ct lint --config ./config.yml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          echo target-branch: main > ./config.yml
          echo helm-extra-args: --timeout 600 >> ./config.yml
          echo validate-maintainers: false >> ./config.yml
          ct install --config ./config.yml
  release:
    needs: lint-test
    runs-on: sw-rancher-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          #charts_dir: ./charts
          config: cr.yaml
        env:
          CR_SKIP_EXISTING: false
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
